# syntax=docker/dockerfile:1.7
# This file is generated by Dofigen v0.0.0
# See https://github.com/lenra-io/dofigen

# runtime
FROM scratch AS runtime
ARG TARGETPLATFORM
WORKDIR /app
COPY \
    --chown=1000:1000 \
    --link \
    "builds/${TARGETPLATFORM}/dofigen" "/bin/"
USER 1000:1000
ENTRYPOINT ["dofigen"]
CMD ["--help"]
