# syntax=docker/dockerfile:1.7
# This file is generated by Dofigen v2.0.0-rc.3
# See https://github.com/lenra-io/dofigen

# muslrust
FROM clux/muslrust@sha256:30d96e0daad305d68fe1798398d5ad92b92e4c4800e42b087d51a34adc340ca2 AS muslrust
ENV \
    CARGO_TARGET="x86_64-unknown-linux-musl" \
    APP_NAME="dofigen" \
    BUILD_ARGS="-F cli"
WORKDIR /app
RUN \
    --mount=type=bind,target=Cargo.toml,source=Cargo.toml \
    --mount=type=bind,target=Cargo.lock,source=Cargo.lock \
    --mount=type=bind,target=src/,source=src/ \
    --mount=type=cache,target=/home/rust/.cargo \
    --mount=type=cache,target=/app/target \
    <<EOF
cargo build --release ${BUILD_ARGS}
mv target/${CARGO_TARGET}/release/${APP_NAME} /tmp/
EOF

# runtime
FROM scratch AS runtime
COPY \
    --from=muslrust \
    --chown=1000:1000 \
    --link \
    "/tmp/dofigen" "/bin/"
USER 1000:1000
ENTRYPOINT ["dofigen"]
CMD ["--help"]
