# syntax=docker/dockerfile:1.7
# This file is generated by Dofigen v2.2.0-beta.1
# See https://github.com/lenra-io/dofigen

# runtime
FROM ubuntu@sha256:278628f08d4979fb9af9ead44277dbc9c92c2465922310916ad0c46ec9999295 AS runtime
COPY \
    --chown=1000:1000 \
    --chmod=555 \
    --link \
    "target/release/dofigen-frontend" "/usr/local/bin/dofigen-frontend"
USER 1000:1000
ENTRYPOINT ["/usr/local/bin/dofigen-frontend"]
