[package]
name = "dofigen"
version = "0.1.0"
edition = "2021"

[[bin]]
edition = "2021"
name = "dofigen"
path = "src/main.rs"

[dependencies]
dofigen_lib = { path = "../dofigen_lib" }
clap = { version = "3.2", features = ["derive"] }
